# Generated by Django 4.0.3 on 2022-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.FloatField(max_length=15)),
                ('last_request_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Symbol Information',
                'verbose_name_plural': 'Symbols Information',
                'ordering': ('symbol',),
            },
        ),
    ]
